language: node_js
node_js:
  - "5.2.0"
before_script:
  - sudo apt-get install python
  - sudo apt-get install python-pip
  - sudo -H pip install numpy
  - cd tests
  - chmod u+x testgen.py
  - ./testgen.py Tests.elm TestsRunner.elm 
  - npm install -g elm elm-test
  - elm-package install -y
script: elm-test TestRunner.elm
